"""Golden query fixtures — generated by build_fixtures.py. Do not edit manually."""

QUERIES = {
    "nvidia_s_revenue_growth_is_primarily_driven_by_its_data_cent": {
        "thesis_plaintext": "NVIDIA's revenue growth is primarily driven by its data center segment rather than gaming",
        "entities": [
            {
                "mentioned_as": "NVIDIA",
                "status": "resolved",
                "name": "NVIDIA Corporation",
                "neid": "01147489026568545706",
                "type": "organization"
            }
        ],
        "claims": [
            "Data center revenue has grown faster than gaming in recent quarterly filings",
            "News coverage of NVIDIA focuses on AI infrastructure rather than gaming"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news"
        ]
    },
    "apple_insiders_have_been_net_sellers_of_company_stock_over_t": {
        "thesis_plaintext": "Apple insiders have been net sellers of company stock over the past year",
        "entities": [
            {
                "mentioned_as": "Apple",
                "status": "resolved",
                "name": "Apple Inc.",
                "neid": "00508379502570440213",
                "type": "organization"
            }
        ],
        "claims": [
            "Recent Form 4 filings show more insider sell transactions than buys",
            "Executive officers have reduced their equity holdings"
        ],
        "data_needs": [
            "filings",
            "relationships",
            "news"
        ]
    },
    "johnson_and_johnson_s_corporate_restructuring_has_improved_i": {
        "thesis_plaintext": "Johnson and Johnson's corporate restructuring has improved its financial profile",
        "entities": [
            {
                "mentioned_as": "Johnson & Johnson",
                "status": "resolved",
                "name": "Johnson & Johnson Incorporated",
                "neid": "06107946766783153625",
                "type": "organization"
            }
        ],
        "claims": [
            "8-K filings document significant organizational changes",
            "Recent 10-Q filings show margin improvement in the company's continuing operations"
        ],
        "data_needs": [
            "filings",
            "events",
            "news"
        ]
    },
    "jpmorgan_chase_is_growing_its_net_interest_income_faster_tha": {
        "thesis_plaintext": "JPMorgan Chase is growing its net interest income faster than Wells Fargo",
        "entities": [
            {
                "mentioned_as": "JPMorgan Chase",
                "status": "resolved",
                "name": "JPMorgan Chase Bank, National Association",
                "neid": "05490061822613857001",
                "type": "organization"
            },
            {
                "mentioned_as": "Wells Fargo",
                "status": "resolved",
                "name": "Wells Fargo & Company",
                "neid": "07076557740071364532",
                "type": "organization"
            }
        ],
        "claims": [
            "JPMorgan's quarterly filings show higher net interest income growth",
            "Wells Fargo's lending growth has been constrained relative to JPMorgan"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news"
        ]
    },
    "microsoft_s_cloud_business_is_growing_faster_than_alphabet_s": {
        "thesis_plaintext": "Microsoft's cloud business is growing faster than Alphabet's cloud division",
        "entities": [
            {
                "mentioned_as": "Microsoft",
                "status": "resolved",
                "name": "Microsoft Corporation",
                "neid": "04562017146718376813",
                "type": "organization"
            },
            {
                "mentioned_as": "Alphabet",
                "status": "resolved",
                "name": "Alphabet",
                "neid": "00146923613514606883",
                "type": "organization"
            }
        ],
        "claims": [
            "Microsoft's cloud segment revenue growth exceeds Google Cloud revenue growth in recent 10-K filings",
            "Both companies identify cloud as a primary growth driver in their annual filings"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news"
        ]
    },
    "pepsico_s_diversified_portfolio_gives_it_more_stable_revenue": {
        "thesis_plaintext": "PepsiCo's diversified portfolio gives it more stable revenue than Coca-Cola",
        "entities": [
            {
                "mentioned_as": "PepsiCo",
                "status": "resolved",
                "name": "PepsiCo, Inc.",
                "neid": "09088580774477053849",
                "type": "organization"
            },
            {
                "mentioned_as": "Coca-Cola",
                "status": "resolved",
                "name": "The Coca-Cola Company",
                "neid": "00904457966722538348",
                "type": "organization"
            }
        ],
        "claims": [
            "PepsiCo's total revenue exceeds Coca-Cola's due to its snack and food segments",
            "Coca-Cola's revenue is more concentrated in beverages per 10-K segment disclosures"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news"
        ]
    },
    "exxonmobil_s_acquisition_activity_positions_it_ahead_of_chev": {
        "thesis_plaintext": "ExxonMobil's acquisition activity positions it ahead of Chevron for production growth",
        "entities": [
            {
                "mentioned_as": "ExxonMobil",
                "status": "resolved",
                "name": "Exxon Mobil Corporation",
                "neid": "05004803275035553382",
                "type": "organization"
            },
            {
                "mentioned_as": "Chevron",
                "status": "resolved",
                "name": "Chevron Corporation",
                "neid": "06578520142381409313",
                "type": "organization"
            }
        ],
        "claims": [
            "ExxonMobil's 8-K filings show more recent acquisition activity than Chevron's",
            "Chevron's quarterly production volume growth trails ExxonMobil's based on recent filings"
        ],
        "data_needs": [
            "filings",
            "events",
            "news",
            "relationships"
        ]
    },
    "apple_microsoft_and_alphabet_hold_the_largest_cash_reserves_": {
        "thesis_plaintext": "Apple, Microsoft, and Alphabet hold the largest cash reserves among US tech companies",
        "entities": [
            {
                "mentioned_as": "Apple",
                "status": "resolved",
                "name": "Apple Inc.",
                "neid": "00508379502570440213",
                "type": "organization"
            },
            {
                "mentioned_as": "Microsoft",
                "status": "resolved",
                "name": "Microsoft Corporation",
                "neid": "04562017146718376813",
                "type": "organization"
            },
            {
                "mentioned_as": "Alphabet",
                "status": "resolved",
                "name": "Alphabet",
                "neid": "00146923613514606883",
                "type": "organization"
            }
        ],
        "claims": [
            "All three report cash and short-term investments exceeding $50 billion in recent quarterly filings",
            "Their combined cash positions have grown year-over-year"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news"
        ]
    },
    "visa_and_mastercard_s_asset_light_network_model_produces_hig": {
        "thesis_plaintext": "Visa and Mastercard's asset-light network model produces higher margins than American Express",
        "entities": [
            {
                "mentioned_as": "Visa",
                "status": "resolved",
                "name": "Visa\u2019s",
                "neid": "00062533344364874061",
                "type": "organization"
            },
            {
                "mentioned_as": "Mastercard",
                "status": "resolved",
                "name": "Mastercard International Incorporated",
                "neid": "02923303755772848268",
                "type": "organization"
            },
            {
                "mentioned_as": "American Express",
                "status": "resolved",
                "name": "American Express Travel Related Services Company, Inc.",
                "neid": "06471664083413765389",
                "type": "organization"
            }
        ],
        "claims": [
            "Visa and Mastercard report higher operating margins than American Express in 10-K filings",
            "American Express carries credit risk on its balance sheet that Visa and Mastercard do not"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news",
            "relationships"
        ]
    },
    "amazon_and_walmart_are_outpacing_target_in_the_retail_compet": {
        "thesis_plaintext": "Amazon and Walmart are outpacing Target in the retail competition",
        "entities": [
            {
                "mentioned_as": "Amazon",
                "status": "resolved",
                "name": "Amazon.com, Inc.",
                "neid": "06901145116483044547",
                "type": "organization"
            },
            {
                "mentioned_as": "Walmart",
                "status": "resolved",
                "name": "Walmart Inc.",
                "neid": "03973586183741664307",
                "type": "organization"
            },
            {
                "mentioned_as": "Target",
                "status": "resolved",
                "name": "Target Corporation",
                "neid": "04707387056215894912",
                "type": "organization"
            }
        ],
        "claims": [
            "Amazon and Walmart's revenue growth in recent quarterly filings exceeds Target's",
            "Target's stock performance has lagged both Amazon and Walmart"
        ],
        "data_needs": [
            "filings",
            "stock_prices",
            "news",
            "events"
        ]
    }
}
